In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv("crime_incidents_messy.csv")

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5250 entries, 0 to 5249
Data columns (total 33 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   incident_id         5250 non-null   object
 1   crime_type          5250 non-null   object
 2   district            5250 non-null   object
 3   city                5250 non-null   object
 4   state               5250 non-null   object
 5   address             5250 non-null   object
 6   latitude            4992 non-null   float64
 7   longitude           4961 non-null   float64
 8   incident_datetime   4910 non-null   object
 9   officer_id          5250 non-null   object
 10  officer_first_name  5250 non-null   object
 11  officer_last_name   5250 non-null   object
 12  badge_number        4938 non-null   float64
 13  suspect_id          4440 non-null   object
 14  suspect_first_name  4440 non-null   object
 15  suspect_last_name   4440 non-null   object
 16  suspect_age         4153 non-null   float64
 17  suspect_gender      3837 non-null   object
 18  suspect_race        3649 non-null   object
 19  victim_id           4993 non-null   object
 20  victim_first_name   4993 non-null   object
 21  victim_last_name    4993 non-null   object
 22  victim_age          4688 non-null   float64
 23  victim_gender       4250 non-null   object
 24  victim_phone        4194 non-null   object
 25  weapon_used         4280 non-null   object
 26  severity            4895 non-null   object
 27  case_status         4519 non-null   object
 28  resolution          4299 non-null   object
 29  num_arrests         4917 non-null   float64
 30  property_loss_usd   4814 non-null   object
 31  reported_online     4746 non-null   object
 32  notes               4181 non-null   object
dtypes: float64(6), object(27)
memory usage: 1.3+ MB

In [10]:
df.describe()

,latitude,longitude,badge_number,suspect_age,victim_age,num_arrests
count,4992.000000,4961.000000,4938.000000,4153.000000,4688.000000,4917.000000
mean,40.778811,-88.607610,5558.581612,48.418493,52.349403,2.262152
std,23.243225,37.214207,2591.581049,43.504819,48.104315,1.994556
min,25.002420,-121.975849,1002.000000,-75.000000,-90.000000,-5.000000
25%,30.966472,-108.040512,3316.250000,29.000000,27.750000,1.000000
50%,36.967123,-94.656440,5567.000000,46.000000,49.000000,2.000000
75%,43.051502,-80.588056,7862.000000,62.000000,71.000000,4.000000
max,199.984200,99.787300,9999.000000,298.000000,298.000000,5.000000

In [15]:
df.isnull().sum()/len(df)*100

incident_id            0.000000
crime_type             0.000000
district               0.000000
city                   0.000000
state                  0.000000
address                0.000000
latitude               4.914286
longitude              5.504762
incident_datetime      6.476190
officer_id             0.000000
officer_first_name     0.000000
officer_last_name      0.000000
badge_number           5.942857
suspect_id            15.428571
suspect_first_name    15.428571
suspect_last_name     15.428571
suspect_age           20.895238
suspect_gender        26.914286
suspect_race          30.495238
victim_id              4.895238
victim_first_name      4.895238
victim_last_name       4.895238
victim_age            10.704762
victim_gender         19.047619
victim_phone          20.114286
weapon_used           18.476190
severity               6.761905
case_status           13.923810
resolution            18.114286
num_arrests            6.342857
property_loss_usd      8.304762
reported_online        9.600000
notes                 20.361905
dtype: float64

In [18]:
df[df.duplicated()].shape

(200, 33)

In [20]:
df["incident_id"].value_counts()

incident_id
INC002391    2
INC002683    2
INC002318    2
INC001986    2
INC002007    2
            ..
INC003156    1
INC003478    1
INC004396    1
INC002554    1
INC003216    1
Name: count, Length: 5050, dtype: int64

In [24]:
df[df["incident_id"]== "INC002683"]

,incident_id,crime_type,district,city,state,address,latitude,longitude,incident_datetime,officer_id,...,victim_gender,victim_phone,weapon_used,severity,case_status,resolution,num_arrests,property_loss_usd,reported_online,notes
942,INC002683,Arson,SOUTHWEST,Hillcrest,TX,8356 Main St,40.99101,NaN,2020-01-01 02:36:50,OFF0045,...,F,NaN,Bat,low,NaN,Arrest Made,3.0,-37694.66,yes,Incident at 8356 Main St. Officer responded at...
4189,INC002683,Arson,SOUTHWEST,Hillcrest,TX,8356 Main St,40.99101,NaN,2020-01-01 02:36:50,OFF0045,...,F,NaN,Bat,low,NaN,Arrest Made,3.0,-37694.66,yes,Incident at 8356 Main St. Officer responded at...

## Removing Dublicates

In [26]:
df.drop_duplicates(inplace= True)

## Handling Missing Values

Removed the Latitide, Longitude and Incident_datetime column because I cannot fill them other wise it will give wrong infromation about place and time of insident. However I have another way to drop latitude and longitude column because I have district, city state and address column

In [30]:
df.columns

Index(['incident_id', 'crime_type', 'district', 'city', 'state', 'address',
       'latitude', 'longitude', 'incident_datetime', 'officer_id',
       'officer_first_name', 'officer_last_name', 'badge_number', 'suspect_id',
       'suspect_first_name', 'suspect_last_name', 'suspect_age',
       'suspect_gender', 'suspect_race', 'victim_id', 'victim_first_name',
       'victim_last_name', 'victim_age', 'victim_gender', 'victim_phone',
       'weapon_used', 'severity', 'case_status', 'resolution', 'num_arrests',
       'property_loss_usd', 'reported_online', 'notes'],
      dtype='object')

In [44]:
df.dropna(subset=["latitude","longitude","incident_datetime"], inplace= True)

In [46]:
df.shape

(4244, 33)

In [62]:
df.isnull().sum()/len(df)*100

incident_id            0.000000
crime_type             0.000000
district               0.000000
city                   0.000000
state                  0.000000
address                0.000000
latitude               0.000000
longitude              0.000000
incident_datetime      0.000000
officer_id             0.000000
officer_first_name     0.000000
officer_last_name      0.000000
badge_number           5.890669
suspect_id             0.000000
suspect_first_name     0.000000
suspect_last_name      0.000000
suspect_age            0.000000
suspect_gender         0.000000
suspect_race           0.000000
victim_id              4.901037
victim_first_name      4.901037
victim_last_name       4.901037
victim_age            10.721018
victim_gender         19.038643
victim_phone          19.745523
weapon_used           18.284637
severity               6.526861
case_status           13.548539
resolution            17.907634
num_arrests            6.338360
property_loss_usd      8.034873
reported_online        9.377945
notes                 20.263902
dtype: float64

Fill "suspect_id" with "SUS00000" for consistency, "suspect_first_name" with  "UNKNOWN" and "suspect_last_name" with "UNKNOWN""

In [50]:
df.fillna({
    "suspect_id" : "SUS00000",
    "suspect_first_name" : "UNKNOWN",
    "suspect_last_name" : "UNKNOWN"
}, inplace= True)

### SUSPECT AGE, SUSPECT GENDER, SUSPECT RACE

Again filled "suspect_age" with median of its age, "suspect_gender" : with mode of gender and "suspect_race" with "Unknown"

In [53]:
df.fillna({
    "suspect_age" : df["suspect_age"].median(),
    "suspect_gender" : df["suspect_gender"].mode()[0],
    "suspect_race" : "Unknown"
}, inplace = True)

### VICTIM ID, FIRST NAME, LAST NAME, AGE, GENDER

In [63]:
df.fillna({
    "victim_id" : "VIC00000",
    "victim_first_name" : "UNKNOWN",
    "victim_last_name" : "UNKNOWN",
    "victim_age" : df["victim_age"].median(),
    "victim_gender" : "UNKNOWN",
    "victim_phone" : "000-000-0000"
    
}, inplace= True)

In [69]:
df.fillna({
    "weapon_used" : "Unknown"
}, inplace = True)

In [74]:
df["severity"]=df["severity"].fillna("Unknown")

In [77]:
df["num_arrests"].unique()

array([nan,  2.,  5.,  1.,  3.,  0., -5.,  4., -1., -2., -4., -3.])

In [79]:
df["case_status"]=df["case_status"].fillna("No Data")
df["resolution"]=df["resolution"].fillna("Unknown")
df["num_arrests"]=df["num_arrests"].fillna(df["num_arrests"].median())
df["property_loss_usd"]=df["property_loss_usd"].fillna("0")
df["reported_online"]=df["reported_online"].fillna(df["reported_online"].mode()[0])
df["notes"]=df["notes"].fillna("No Available Notes")
df["badge_number"]=df["badge_number"].fillna(df["badge_number"].median())

In [80]:
df.isnull().sum()/len(df)*100

incident_id           0.0
crime_type            0.0
district              0.0
city                  0.0
state                 0.0
address               0.0
latitude              0.0
longitude             0.0
incident_datetime     0.0
officer_id            0.0
officer_first_name    0.0
officer_last_name     0.0
badge_number          0.0
suspect_id            0.0
suspect_first_name    0.0
suspect_last_name     0.0
suspect_age           0.0
suspect_gender        0.0
suspect_race          0.0
victim_id             0.0
victim_first_name     0.0
victim_last_name      0.0
victim_age            0.0
victim_gender         0.0
victim_phone          0.0
weapon_used           0.0
severity              0.0
case_status           0.0
resolution            0.0
num_arrests           0.0
property_loss_usd     0.0
reported_online       0.0
notes                 0.0
dtype: float64

# Fixing Inconsistence Formating

In [83]:
df["crime_type"]= df["crime_type"].str.title().str.strip()

In [152]:
df["case_status"].unique()

array(['Open', 'No Data', 'Closed', 'Resolved', 'Under Investigation',
       'Investgation', 'Pendng', 'Pending'], dtype=object)

In [86]:
df["district"]= df["district"].str.title().str.strip()

In [88]:
df["district"]= df["district"].replace({"Sou":"South",
                                        "Cen":"Central",
                                        "Eas":"East",
                                        "Nor":"North",
                                        "Mid":"Midtown",
                                        "Wes":"West"
                                       })

In [89]:
df["district"].unique()

array(['South', 'Southeast', 'Southwest', 'Central', 'North', 'East',
       'Midtown', 'Northeast', 'West', 'Northwest'], dtype=object)

In [90]:
df["city"].unique()

array(['Maplewood', 'Lakewood', 'Springfield', 'Hillcrest', 'Centerville',
       'Riverside', 'Oakdale', 'Fairview'], dtype=object)

In [91]:
df["state"].unique()

array(['GA', 'OH', 'AZ', 'PA', 'CA', 'TX', 'IL', 'NY', 'FL', 'NC'],
      dtype=object)

In [98]:
df["officer_first_name"]= df["officer_first_name"].str.title().str.strip()
df["officer_last_name"]= df["officer_last_name"].str.title().str.strip()

In [101]:
df["suspect_first_name"]= df["suspect_first_name"].str.title().str.strip()
df["suspect_last_name"]= df["suspect_last_name"].str.title().str.strip()

In [107]:
df["victim_age"]=df["victim_age"].abs()
df["suspect_age"]=df["suspect_age"].abs()

In [105]:
df["victim_age"].unique()

array([ 51., 231.,  29., 243.,  15.,  72.,  50.,  55.,  10.,  47.,  35.,
        41.,  26.,  82.,  49.,  12.,  33., 292.,  64.,  69.,  36.,  43.,
        74.,  83.,  17.,  80.,  21.,  65.,  73.,  39.,  23.,  38.,  19.,
        78.,  54.,  18.,  45.,  90.,  88.,  59., 287.,  68.,  32.,  13.,
        56.,  66., 157.,  40., 263.,  37.,  75., 190.,  63.,  61.,  30.,
        81.,  11., 296.,  16.,  60.,  84.,  70.,  87.,  57.,  62.,  89.,
       219.,  27.,  28.,  24.,  52., 264.,  76., 195.,  53.,  14.,  44.,
        79.,  34.,  67.,  42.,  22.,  20.,  48., 240., 215.,  46.,  86.,
       181.,  58., 254.,  77.,  71., 297., 266.,  31., 176.,  25., 280.,
        85., 167., 278., 153., 152., 203., 182., 218., 177., 298., 212.,
       185., 168., 235., 199., 158., 229., 274., 225., 285., 162., 220.,
       205., 232., 272., 238., 160., 202., 242., 161., 175., 221., 245.,
       255., 250., 226., 269., 277., 186., 271., 291., 279., 246., 258.,
       282., 281., 275., 198., 227., 295., 151., 294., 163., 265., 208.,
       236., 193., 237., 270., 170., 217., 228., 210., 252., 286., 206.,
       200., 180., 207., 213., 192., 159., 256., 239., 165., 183., 234.,
       194., 150.])

In [149]:
df["severity"].unique()

array(['Medium', 'High', 'Low', 'Unknown', 'Critical'], dtype=object)

In [110]:
df["suspect_gender"] = df["suspect_gender"].str.title().str.strip()

In [112]:
df["suspect_gender"] = df["suspect_gender"].replace({"M" : "Male", "F" : "Female"})

In [115]:
df["suspect_race"] = df["suspect_race"].str.title().str.strip()

In [117]:
df["victim_first_name"]= df["victim_first_name"].str.title().str.strip()
df["victim_last_name"]= df["victim_last_name"].str.title().str.strip()

In [119]:
df["victim_gender"] = df["victim_gender"].str.title().str.strip()

In [121]:
df["victim_gender"] = df["victim_gender"].replace({"M" : "Male", "F" : "Female"})

In [134]:
df["victim_phone"]=df["victim_phone"].str.replace("-","")

In [138]:
df["victim_phone"]=df["victim_phone"].apply(lambda x : x[0:3]+"-"+x[3:6]+"-"+x[6:10])

In [140]:
df["weapon_used"]=df["weapon_used"].str.title().str.strip()

In [142]:
df["severity"]=df["severity"].str.title().str.strip()

In [148]:
df["severity"]=df["severity"].replace({"1" : "Low", "2" : "Medium", "3" : "High", "4" : "Critical","Crit" : "Critical","Med" : "Medium"})

In [151]:
df["case_status"]=df["case_status"].str.title().str.strip()

In [154]:
df["case_status"] = df["case_status"].replace({"Under Investigation" : "Investigation",
                                               "Investgation" : "Investigation",
                                               "Pendng" : "Pending"
                                              })

In [157]:
df["resolution"]=df["resolution"].str.title().str.strip()

In [159]:
df["resolution"] = df["resolution"].replace({"Warning" : "Warning Issued", "Dismissed" : "Case Dismissed", 
                                             "Arres Made": "Arrest Made"})

In [162]:
df["num_arrests"]=df["num_arrests"].abs()

In [166]:
df["reported_online"]=df["reported_online"].str.title().str.strip()

In [169]:
df["reported_online"] = df["reported_online"].replace({"True" : "Yes", "False" : "No", "0":"No", "1": "Yes"})

In [171]:
df["notes"]=df["notes"].str.title().str.strip()

In [174]:
df[df.duplicated()]

Empty DataFrame
Columns: [incident_id, crime_type, district, city, state, address, latitude, longitude, incident_datetime, officer_id, officer_first_name, officer_last_name, badge_number, suspect_id, suspect_first_name, suspect_last_name, suspect_age, suspect_gender, suspect_race, victim_id, victim_first_name, victim_last_name, victim_age, victim_gender, victim_phone, weapon_used, severity, case_status, resolution, num_arrests, property_loss_usd, reported_online, notes]
Index: []

[0 rows x 33 columns]

# Data Types

In [179]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4244 entries, 0 to 5249
Data columns (total 33 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   incident_id         4244 non-null   object
 1   crime_type          4244 non-null   object
 2   district            4244 non-null   object
 3   city                4244 non-null   object
 4   state               4244 non-null   object
 5   address             4244 non-null   object
 6   latitude            4244 non-null   float64
 7   longitude           4244 non-null   float64
 8   incident_datetime   4244 non-null   datetime64[ns]
 9   officer_id          4244 non-null   object
 10  officer_first_name  4244 non-null   object
 11  officer_last_name   4244 non-null   object
 12  badge_number        4244 non-null   float64
 13  suspect_id          4244 non-null   object
 14  suspect_first_name  4244 non-null   object
 15  suspect_last_name   4244 non-null   object
 16  suspect_age         4244 non-null   float64
 17  suspect_gender      4244 non-null   object
 18  suspect_race        4244 non-null   object
 19  victim_id           4244 non-null   object
 20  victim_first_name   4244 non-null   object
 21  victim_last_name    4244 non-null   object
 22  victim_age          4244 non-null   float64
 23  victim_gender       4244 non-null   object
 24  victim_phone        4244 non-null   object
 25  weapon_used         4244 non-null   object
 26  severity            4244 non-null   object
 27  case_status         4244 non-null   object
 28  resolution          4244 non-null   object
 29  num_arrests         4244 non-null   float64
 30  property_loss_usd   4244 non-null   object
 31  reported_online     4244 non-null   object
 32  notes               4244 non-null   object
dtypes: datetime64[ns](1), float64(6), object(26)
memory usage: 1.2+ MB

In [178]:
df["incident_datetime"]= pd.to_datetime(df["incident_datetime"],format = "mixed")

In [183]:
df["incident_datetime"]

0      2024-04-16 08:45:03
1      2022-01-11 22:03:29
2      2022-04-14 11:39:24
3      2020-12-09 15:14:24
4      2021-07-24 20:08:13
               ...
5245   2021-12-18 17:27:18
5246   2023-06-23 04:09:19
5247   2018-04-25 14:38:24
5248   2023-03-29 09:54:50
5249   2022-09-08 00:00:00
Name: incident_datetime, Length: 4244, dtype: datetime64[ns]

In [216]:
# See unique bad values
bad_values = df[df["property_loss_usd"].str.contains(r'\.\d+\.', regex=True, na=False)]["property_loss_usd"].unique()
print(bad_values)

['35446.9.0' '42423.94.0' '1982.33.0' '38013.69.0' '30962.38.0'
 '46792.6.0' '38839.72.0' '18339.64.0' '20766.39.0' '35114.22.0'
 '14381.15.0' '35313.73.0' '12733.23.0' '10947.07.0' '44289.89.0'
 '44937.9.0' '35925.45.0' '10147.07.0' '4850.55.0' '7184.8.0' '43314.61.0'
 '35687.46.0' '11069.15.0' '41542.39.0' '24821.41.0' '28199.98.0'
 '10960.51.0' '26052.11.0' '680.33.0' '45607.86.0' '44932.57.0'
 '44184.19.0' '13564.42.0' '30883.2.0' '8353.41.0' '34886.91.0'
 '2247.99.0' '33859.81.0' '26861.93.0' '43735.21.0' '4725.89.0'
 '33633.87.0' '9299.21.0' '2551.45.0' '30290.17.0' '39011.22.0'
 '5294.74.0' '17988.85.0' '28833.57.0' '48192.83.0' '10576.68.0'
 '48971.1.0' '34312.44.0' '24088.08.0' '60.75.0' '1034.9.0' '23161.47.0'
 '46518.02.0' '1509.5.0' '26390.26.0' '30851.47.0' '2092.92.0' '36471.8.0'
 '34964.02.0' '9701.66.0' '29621.71.0' '22120.59.0' '28153.57.0'
 '27513.23.0' '27176.37.0' '39166.12.0' '42073.36.0' '19424.02.0'
 '5375.81.0' '12110.16.0' '41860.21.0' '27975.26.0' '1245.61.0' '753.64.0'
 '3124.14.0' '46737.55.0' '14648.96.0' '30318.62.0' '17995.21.0'
 '17748.57.0' '20066.34.0' '18256.48.0' '36116.45.0' '10640.77.0'
 '22674.82.0' '22561.36.0' '16136.96.0' '37611.46.0' '9734.37.0'
 '48682.79.0' '9946.8.0' '3094.25.0' '26.8.0' '42466.38.0' '25859.93.0'
 '35933.29.0' '10895.13.0' '18910.34.0' '42519.78.0' '645.91.0'
 '26090.98.0' '42863.99.0' '29292.96.0' '5799.12.0' '2479.37.0'
 '2112.43.0' '30566.7.0' '7870.46.0' '6755.18.0' '22188.67.0']

In [217]:
# Keep only first decimal point
df["property_loss_usd"] = df["property_loss_usd"].str.replace(r'^(\d+\.\d+)\..*$', r'\1', regex=True)

In [218]:
df["property_loss_usd"] = pd.to_numeric(df["property_loss_usd"], errors="coerce")

In [199]:
df.drop(["incident_date", "incident_time"], axis=1, inplace=True)

In [219]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4244 entries, 0 to 5249
Data columns (total 33 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   incident_id         4244 non-null   object
 1   crime_type          4244 non-null   object
 2   district            4244 non-null   object
 3   city                4244 non-null   object
 4   state               4244 non-null   object
 5   address             4244 non-null   object
 6   latitude            4244 non-null   float64
 7   longitude           4244 non-null   float64
 8   incident_datetime   4244 non-null   datetime64[ns]
 9   officer_id          4244 non-null   object
 10  officer_first_name  4244 non-null   object
 11  officer_last_name   4244 non-null   object
 12  badge_number        4244 non-null   float64
 13  suspect_id          4244 non-null   object
 14  suspect_first_name  4244 non-null   object
 15  suspect_last_name   4244 non-null   object
 16  suspect_age         4244 non-null   float64
 17  suspect_gender      4244 non-null   object
 18  suspect_race        4244 non-null   object
 19  victim_id           4244 non-null   object
 20  victim_first_name   4244 non-null   object
 21  victim_last_name    4244 non-null   object
 22  victim_age          4244 non-null   float64
 23  victim_gender       4244 non-null   object
 24  victim_phone        4244 non-null   object
 25  weapon_used         4244 non-null   object
 26  severity            4244 non-null   object
 27  case_status         4244 non-null   object
 28  resolution          4244 non-null   object
 29  num_arrests         4244 non-null   float64
 30  property_loss_usd   4244 non-null   float64
 31  reported_online     4244 non-null   object
 32  notes               4244 non-null   object
dtypes: datetime64[ns](1), float64(7), object(25)
memory usage: 1.2+ MB

# Outliers

In [201]:
def calculate (age):
    if age > 100:
        return 100
    else:
        return age

In [202]:
df["suspect_age"]

0        51.0
1        28.0
2        19.0
3       262.0
4        75.0
        ...
5245     60.0
5246     36.0
5247     46.0
5248     35.0
5249     46.0
Name: suspect_age, Length: 4244, dtype: float64

In [206]:
df["suspect_age"]=df["suspect_age"].apply(calculate)
df["victim_age"]=df["victim_age"].apply(calculate)

In [210]:
df.to_csv("Clean Crime Insident.csv")